export function fixWorkflow(json: any) {
  const safe = structuredClone(json || {});

  // Fix missing arrays
  safe.nodes = Array.isArray(safe.nodes) ? safe.nodes : [];
  safe.edges = Array.isArray(safe.edges) ? safe.edges : [];
  safe.execution_plan = Array.isArray(safe.execution_plan)
    ? safe.execution_plan
    : [];

  // Fill missing workflow name
  if (!safe.workflow_name) {
    safe.workflow_name = "Enterprise Workflow";
  }

  if (!safe.workflow_summary) {
    safe.workflow_summary = "Auto-repaired workflow generated by ContextOS";
  }

  if (safe.nodes.length < 8) {
    safe.nodes = [
      {
        id: "fallback-hr",
        type: "default",
        layout: { lane: "hr", position: 0 },
        data: {
          label: "Human Resources",
          nodeType: "department",
          department: "hr",
          status: "pending",
          description: "Fallback HR node",
          dependsOn: [],
          riskLevel: "low",
        },
      },
      ...Array.from({ length: 7 }, (_, i) => ({
        id: `fallback-node-${i}`,
        type: "default",
        layout: { lane: "it", position: i + 1 },
        data: {
          label: `Fallback Step ${i + 1}`,
          nodeType: "action",
          department: "it",
          status: "pending",
          description: "Auto-injected step",
          dependsOn: i === 0 ? ["fallback-hr"] : [`fallback-node-${i - 1}`],
          riskLevel: "low",
        },
      }))
    ];
    
    // Auto-generate edges for fallback nodes
    safe.edges = safe.nodes.map((n: any, i: number, arr: any[]) => {
      if (i === 0) return null;
      return {
        id: `edge-${arr[i-1].id}-${n.id}`,
        source: arr[i-1].id,
        target: n.id,
        type: "smoothstep",
        animated: true,
      }
    }).filter(Boolean);
  }

  // Fix broken nodes
  safe.nodes = safe.nodes.map((n: any, i: number) => ({
    id: n?.id || `node-${i}`,
    type: "default",
    layout: n?.layout || { lane: "it", position: i },
    data: {
      label: n?.data?.label || "Unknown Node",
      nodeType: n?.data?.nodeType || "action",
      department: n?.data?.department || "it",
      status: "pending",
      description: n?.data?.description || "",
      dependsOn: n?.data?.dependsOn || [],
      riskLevel: n?.data?.riskLevel || "low",
    },
  }));

  return safe;
}