import { GoogleGenAI } from "@google/genai";
import { RUNTIME_SYSTEM_INSTRUCTION } from "@/lib/prompts/runtime/executePrompt";

export async function executeWorkflow(
  workflow: any,
  runtimeCtx: any,
  preferredModel: string = "gemini-3-flash-preview",
  options: { getSpeed?: () => number } = {}
) {
  const getSpeed = options.getSpeed || (() => 1);

  function delay(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms / getSpeed()));
  }
  const { startExecution, stopExecution, addLog, completeStep, addSecurityEvent } = runtimeCtx;

  if (!workflow || !workflow.nodes) {
    console.error("No workflow to execute");
    return;
  }

  startExecution();

  // Sort nodes based on layout order or dependencies
  const nodes = [...workflow.nodes].sort((a, b) => {
    return (a.layout?.order || 0) - (b.layout?.order || 0);
  });

  const now = () => {
    const d = new Date();
    return d.toLocaleTimeString('en-US', { hour12: true, hour: '2-digit', minute: '2-digit', second: '2-digit' });
  };

  addLog({
    id: Date.now().toString(),
    timestamp: now(),
    message: '[ORCHESTRATOR] Starting workflow orchestration sequence...'
  });

  const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "AI_STUDIO_FREE_TIER" });
  let preGeneratedResults: any = null;

  try {
    const actionNodes = nodes.filter(n => n.data?.nodeType !== 'department' && n.data?.nodeType !== 'system');

    addLog({
      id: Date.now().toString() + Math.random(),
      timestamp: now(),
      message: '[ORCHESTRATOR] Planning execution path and payload schemas...'
    });

    const runtimePayload = {
      target: { employee: "Sarah Chen", employee_id: "EMP-89422" },
      nodes: actionNodes.map(n => ({
        id: n.id,
        label: n.data.label,
        department: n.data.department,
        risk: n.data.riskLevel
      })),
    };

    const systemInstructionText = RUNTIME_SYSTEM_INSTRUCTION;
    const aiText = JSON.stringify(runtimePayload);

    const allModels = ['gemini-3.1-pro-preview', 'gemini-3-flash-preview', 'gemini-2.5-pro', 'gemini-2.5-flash'];

    let fallbackModel = preferredModel;
    if (preferredModel === "gemini-3.1-pro-preview") fallbackModel = "gemini-2.5-pro";
    if (preferredModel === "gemini-3-flash-preview") fallbackModel = "gemini-2.5-flash";

    const modelsToTry = [preferredModel, fallbackModel, ...allModels.filter(m => m !== preferredModel && m !== fallbackModel)];
    let responseText = "";

    for (const model of modelsToTry) {
      try {
        if (runtimeCtx.setAiModel) {
          runtimeCtx.setAiModel(model);
        }
        const response = await ai.models.generateContent({
          model: model,
          contents: [{ role: 'user', parts: [{ text: aiText }] }],
          config: {
            responseMimeType: "application/json",
            systemInstruction: systemInstructionText
          }
        });
        responseText = response.text || "";
        if (responseText) {
          console.log(`Execution simulation generated by ${model}`);
          break;
        }
      } catch (err: any) {
        console.warn(`Model ${model} failed in executeWorkflow single-shot:`, err.message || err);
        if (model.includes("3.1")) {
          // We don't bother toasting here again to avoid double toasts, as generation failure toast already happened in generateWorkflow.
          console.log(`Failed to execute with ${model}, falling back...`);
        } else if (!err.message?.includes('429') && !err.message?.includes('RESOURCE_EXHAUSTED')) {
          throw err;
        }
      }
    }

    if (responseText) {
      preGeneratedResults = JSON.parse(responseText.trim());
    }
  } catch (error: any) {
    console.warn("AI generation for execution loop failed, using fallback mock data locally:", error.message);
  }

  let highRiskCount = 0;

  let finalDecision: 'approved' | 'denied' | 'none' = 'none';

  for (const node of nodes) {
    if (node.data?.nodeType === 'department' || node.data?.nodeType === 'system') {
      completeStep(node.id); // Auto-complete structural nodes
      continue;
    }

    const dept = (node.layout?.lane || node.data?.department || 'SYSTEM').toUpperCase();

    // Announce orchestration
    addLog({
      id: Date.now().toString() + Math.random(),
      timestamp: now(),
      message: `[ORCHESTRATOR] Initiating orchestration for task: ${node.data.label}...`
    });

    try {
      let isExplicitlyBlocked = false;
      if (node.data?.riskLevel === 'high') {
        highRiskCount++;
        // On the second high-risk node, we intentionally block it to simulate hard blocks
        if (highRiskCount === 2 || node.data?.label?.toLowerCase().includes('archive') || node.data?.label?.toLowerCase().includes('export')) {
          isExplicitlyBlocked = true;
        }
      }

      if (isExplicitlyBlocked) {
        // Halt downstream processing but trigger escalation first
        const failMessage = `Attempted action '${node.data.label}' violated edge isolation policy SEC-447. Veea manual approval required.`;
        addLog({
          id: Date.now().toString() + Math.random(),
          timestamp: now(),
          message: `[SECURITY] SEC-447 Data Exfiltration Guard triggered.`
        });
        await delay(600 + Math.random() * 800);
        addLog({
          id: Date.now().toString() + Math.random(),
          timestamp: now(),
          message: `[GOVERNANCE] Execution path quarantined pending human approval.`
        });
        await delay(500 + Math.random() * 700);
        addLog({
          id: Date.now().toString() + Math.random(),
          timestamp: now(),
          message: `[ORCHESTRATOR] Dependent operations suspended.`
        });

        runtimeCtx.addSecurityEvent({
          id: Date.now().toString(),
          status: 'BLOCK',
          message: failMessage,
          timestamp: now(),
          policyContext: 'SEC-447 Data Exfiltration Guard'
        });

        // Trigger escalation and wait
        if (runtimeCtx.triggerEscalation) {
          const decision = await runtimeCtx.triggerEscalation({
            policy: 'SEC-447',
            riskLevel: 'Critical',
            department: dept,
            requestedAction: node.data.label,
            reason: 'Sensitive data export attempted across isolated edge boundary.',
            nodeId: node.id
          });

          finalDecision = decision;

          if (decision === 'approved') {
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[GOVERNANCE] Manual approval received from Security Officer.`
            });
            await delay(800 + Math.random() * 1000);
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[ORCHESTRATOR] Resuming suspended execution path.`
            });
            await delay(900 + Math.random() * 600);
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[${dept}] Sandbox validated. Continuing secure processing...`
            });
            isExplicitlyBlocked = false; // allow to continue below
          } else {
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[GOVERNANCE] Execution denied by Security Officer.`
            });
            await delay(700 + Math.random() * 800);
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[ORCHESTRATOR] Terminating branch execution.`
            });
            await delay(600 + Math.random() * 500);
            addLog({
              id: Date.now().toString() + Math.random(),
              timestamp: now(),
              message: `[SECURITY] Incident record SEC-447-2026 archived.`
            });

            runtimeCtx.failStep(node.id); // It remains failed
            break; // Hard abort out of the workflow loop!
          }
        } else {
          runtimeCtx.failStep(node.id);
          break;
        }
      }

      let runtimeResult;

      const isDelete = node.data?.label?.toLowerCase().includes('delete') || node.data?.label?.toLowerCase().includes('revoke');

      if (preGeneratedResults && preGeneratedResults.node_results && preGeneratedResults.node_results[node.id]) {
        runtimeResult = preGeneratedResults.node_results[node.id];
      } else {
        runtimeResult = {
          execution_status: "completed",
          execution_summary: `Executed ${node.data.label} via fallback mock.`,
          system_logs: [
            `Connecting to ${dept} API endpoint...`,
            `Authenticating as ContextOS service account...`,
            `Executing action: ${node.data.label}`,
            `Action confirmed by upstream system.`
          ],
          mock_payload_sent: {
            endpoint: `api.enterprise.internal/v1/${dept.toLowerCase()}/action`,
            method: isDelete ? "DELETE" : "POST",
            body: { target: "EMP-89422", action: node.data.label }
          }
        };
      }

      // Add random variation like retries or queued states
      if (dept === 'SLACK' && Math.random() > 0.5) {
        runtimeResult.system_logs.splice(1, 0, `WARN: Slack SCIM API timeout detected. Retrying request in 2s...`);
        runtimeResult.system_logs.splice(2, 0, `INFO: Retry successful. Request acknowledged.`);
      }

      if (dept === 'IT' && Math.random() > 0.5) {
        runtimeResult.system_logs.push(`INFO: Waiting for Google Workspace directory propagation...`);
      }

      if (node.data?.label?.toLowerCase().includes('payroll')) {
        runtimeResult.system_logs.push(`INFO: Payroll batch operation queued for processing.`);
      }

      // Stream the system telemetry out
      // Redact financial figures from finance/payroll logs to enforce DLP governance
      const isFinancialDept = ['FINANCE', 'HR'].includes(dept) || node.data?.label?.toLowerCase().includes('payroll');
      if (runtimeResult.system_logs && Array.isArray(runtimeResult.system_logs)) {
        for (let logLine of runtimeResult.system_logs) {
          if (isFinancialDept) {
            // Mask exact dollar amounts — showing these contradicts the data exfiltration governance story
            logLine = logLine.replace(/\$[\d,]+\.?\d*/g, '[REDACTED-FINANCIAL]');
          }
          addLog({
            id: Date.now().toString() + Math.random(),
            timestamp: now(),
            message: `[${dept}] ${logLine}`
          });
          await delay(200 + Math.random() * 400); // realistic streaming effect with jitter
        }
      }

      // Add high risk intercepts logic dynamically
      if (node.data?.riskLevel === 'high' && !isExplicitlyBlocked) {
        const messages = [
          "Privilege escalation detected at the edge. Awaiting Veea IAM authorization.",
          "Sensitive operation routed for Veea Edge processing review.",
          "Veea Trusted Edge Enclave (vTTE) verification required before execution continues.",
          "Action temporarily held in Veea Zero-Trust isolation for IAM verification."
        ];
        const randomMessage = messages[Math.floor(Math.random() * messages.length)];

        const policies = [
          "IAM-221 Privileged Access Review",
          "FIN-014 Financial Integrity Check",
          "SEC-991 Device Wipe Validation",
          "IAM-104 Zero-Trust Token Verification"
        ];
        const randomPolicy = policies[Math.floor(Math.random() * policies.length)];

        addSecurityEvent({
          id: Date.now().toString(),
          status: 'REVIEW',
          message: `High risk action intercepted: ${node.data.label}`,
          timestamp: now(),
          policyContext: randomPolicy
        });
        await delay(800 + Math.random() * 1200);
        addLog({
          id: Date.now().toString() + Math.random(),
          timestamp: now(),
          message: `[VEEA-SHIELD] ${randomMessage}`
        });

        await delay(1200 + Math.random() * 1000);
        addLog({
          id: Date.now().toString() + Math.random(),
          timestamp: now(),
          message: `[GOVERNANCE] Execution paused pending IAM verification.`
        });

        await delay(1500 + Math.random() * 1000);
        addSecurityEvent({
          id: (Date.now() + 1).toString(),
          status: 'PASS',
          message: `IAM verified. Proceeding with ${node.data.label}`,
          timestamp: now(),
          policyContext: randomPolicy
        });

        addLog({
          id: (Date.now() + 1).toString(),
          timestamp: now(),
          message: `[ORCHESTRATOR] Task resumed.`
        });
        await delay(600 + Math.random() * 500);
      }

      // Update System States
      if (dept === 'HR') {
        runtimeCtx.updateSystemState('hr', { employment: 'Terminated' });
      }
      if (dept === 'IT') {
        runtimeCtx.updateSystemState('google', { accountSuspended: true });
        if (node.data?.label?.toLowerCase().includes('transfer')) {
          runtimeCtx.updateSystemState('google', { driveTransfer: 'Complete' });
        }
      }
      if (dept === 'SLACK' || node.data?.label?.toLowerCase().includes('slack')) {
        runtimeCtx.updateSystemState('slack', { sessionsRevoked: 3, access: 'Disabled' });
      }
      if (node.data?.label?.toLowerCase().includes('payroll') || node.data?.department === 'finance') {
        runtimeCtx.updateSystemState('hr', { payroll: 'Pending' });
      }

      completeStep(node.id);
      addLog({
        id: Date.now().toString() + Math.random(),
        timestamp: now(),
        message: `[ORCHESTRATOR] Task ${node.id} successfully marshaled: ${runtimeResult.execution_summary || 'Task completed'}`
      });

    } catch (error: any) {
      console.error(`Orchestration failed at node ${node.id}:`, error);
      addLog({
        id: Date.now().toString() + Math.random(),
        timestamp: now(),
        message: `[CRITICAL] Orchestration engine stalled at node ${node.id}. Safety fallback engaged.`
      });
      break;
    }

    await delay(800 + Math.random() * 1200); // pseudo-random pausing between nodes
  }

  await delay(400 + Math.random() * 600);

  const hasDenied = finalDecision === 'denied';

  if (hasDenied) {
    addLog({
      id: Date.now().toString() + Math.random(),
      timestamp: now(),
      message: '[ORCHESTRATOR] 1 execution path terminated due to policy violation.'
    });
  } else {
    addLog({
      id: Date.now().toString() + Math.random(),
      timestamp: now(),
      message: '[ORCHESTRATOR] Workflow execution completed successfully.'
    });
  }

  stopExecution();
}
